{{
    Vite::useHotFile(public_path('hot')) // Customize the "hot" file...
        ->useBuildDirectory('build') // Customize the build directory...
        ->useManifestFilename('manifest.json') // Customize the manifest filename...
        ->withEntryPoints(['resources/js/app.js'])
}}