dist: xenial
language: php

php:
    - '7.2'

services:
  - mysql

addons:
   chrome: stable

install:
  - travis_retry composer self-update
  - travis_retry composer install --no-interaction
  - ./vendor/bin/dusk-updater update

cache:
  directories:
    - $HOME/.composer/cache

before_install:
  - mysql -e 'CREATE DATABASE crudadmin_v2_test;'

script: vendor/bin/phpunit