dist: xenial
language: php

php:
    - '7.2'

services:
  - mysql

addons:
   chrome: stable

before_install:
  - mysql -e 'CREATE DATABASE crudadmin_v2_test;'
  - travis_retry composer self-update

install:
  - travis_retry composer install --no-interaction
  - travis_retry composer update crudadmin/resources crudadmin/framework --no-interaction
  - ./vendor/bin/dusk-updater update

cache:
  directories:
    - $HOME/.composer/cache

script: vendor/bin/phpunit