<?php

return [
    'admin' => 'Administration',
    'logout' => 'Sign Out',
    'welcome' => 'Welcome',
    'welcome-in-admin' => 'Welcome to admin',

    'admin-user' => 'Administrator',
    'auto-logout' => 'You were automatically logged off. Please sign in again.',
    'unknown-error' => 'An error occurred unexpectedly, please try again later',

    'navigation' => 'Navigation',
    'language-mutation' => 'Language version',
    'language-title' => 'Modify language mutation settings. Also, set your default language by placing your language in the first position.',
    'languages-add-new' => 'Add new language',
    'languages-update' => 'You are editing language: name',
    'languages-name' => 'Language name',
    'languages-title' => 'Enter the name of the language',
    'languages-prefix' => 'Language abbreviation',
    'languages-prefix-title' => 'Enter your language (en, sk, de, cz) ...',
    'languages-po-name' => 'Translation .po file for poedit',
    'languages-mo-name' => 'Translation .mo file for poedit',
    'languages' => 'Language mutation',
    'change-language' => 'Change language mutation. WARNING! Changing your language may discard your currently delineated changes.',

    'super-admin' => 'Super Admin',
    'admin-group' => 'Allowed admin models',
    'user-groups' => 'Admin groups',
    'user-groups-title' => 'Change group permissions',
    'user-groups-name' => 'Group name',
    'user-groups-placeholder' => 'Fill group name',
    'user-groups-modules' => 'Allowed modules',

    'show' => 'Show',
    'show-image' => 'Show image',
    'download' => 'Download',
    'download-document' => 'Download document',
    'download-file' => 'Download file',

    'history.changes' => 'History of Changes',
    'history.who' => 'Changes done',
    'history.count' => 'Number of Changes',
    'history.date' => 'Change date',
    'history.system' => 'System',

    'close' => 'Close',
    'accept' => 'Confirm',
    'loading' => 'Loading data ...',

    'created' => 'Created',
    'created-at' => 'Created on',
    'last-change' => 'Last Change',
    'published-at' => 'Published on',

    'info' => 'Information',
    'warning' => 'Warning',
    'row-info' => 'Record Information',
    'row-info-n' => 'Record Information No.',
    'no-changes' => 'No changes have been made to the current record.',
    'delete-warning' => 'Are you sure you want to delete the record?',

    'cannot-create' => 'Can not add new record.',
    'cannot-edit' => 'This row can not be edited.',
    'cannot-delete' => 'This row can not be deleted.',
    'cannot-publish' => 'This row can not be unpublished.',
    'cannot-sort' => 'This row can not be moved.',
    'success-created' => 'Record successfully added',
    'success-save' => 'Record Saved successfully',
    'with-errors' => 'with the following errors',

    'multilanguages' => 'This record is multilanguage',
    'rows' => 'Items',
    'saving' => 'Save',
    'save' => 'Save',
    'send' => 'Send',
    'sending' => 'Sending',
    'edit-row-n' => 'Edit Record No.',
    'new-row' => 'New row',
    'general-tab' => 'General',
    'number' => 'No.',
    'rows-list' => 'Columns list',
    'default' => 'Default',

    'edit' => 'Edit',
    'show' => 'Show',
    'hide' => 'Hide',
    'delete' => 'Delete',
    'delete-file' => 'Delete file',
    'select-option' => 'Select one of the options',
    'select-option-multi' => 'Select from list of options',
    'no-option' => 'No option',

    'edit-size' => 'Adjust the width of the form view for a more readable display of records',
    'search' => 'Search',
    'search-all' => 'Search everywhere',
    'get-value' => 'Select value',
    'on' => 'Off',
    'off' => 'On',
    'yes' => 'Yes',
    'no' => 'No',

    'rows-count' => 'Number of records in a table',
    'show-all' => 'Show all',
    'confirmation' => 'verify again',

    'success-save' => 'Changes saved successfully.',
    'no-permissions' => 'You have no authority to access this section.',
    'migrate-error' => 'An unexpected error has occurred, you probably did not trigger the migration of the models with the command:',
    'db-error' => 'Unexpected error occurred. Your administrator may have forgotten to update the database. If this error persists, please contact him / her.',
    'row-error' => 'The record does not exist, probably has already been deleted.',
    'component-missing' => 'Component <strong>%s</ strong> for <strong>%s</ strong> field was not found.',
    'lang-error' => 'Please check default language values. Some of them are required.',

    'login' => 'Login',
    'password' => 'Password',
    'password-again' => 'Password again',
    'login-with' => 'Please log in using email and password',
    'remember-password' => 'Remember',
    'forgot-password' => 'Forgot password',
    'send-password' => 'Send confirmation link to email',
    'password-reset' => 'Password reset request',
    'password-reset-button' => 'Reset password',
    'tab-error' => 'The tab has no filled all required information.',
];