<?php

return [
    'admin' => 'Administrace',
    'logout' => 'Odhlásit',
    'welcome' => 'Vítejte',
    'welcome-in-admin' => 'Vítejte v administraci',

    'admin-user' => 'Administrátor',
    'auto-logout' => 'Byli jste automatický odhlášeni. Prosím, znovu se přihlaste.',
    'unknown-error' => 'Nastala nečekaná chyba, zkuste později prosím.',

    'navigation' => 'Navigace',
    'language-mutation' => 'Jazykové verze',
    'language-title' => 'Upravte si nastavení jazykových mutaci. Také si nastavte výchozí jazyk umístěním jazyka na první pozici.',
    'languages-add-new' => 'Přidat nový jazyk',
    'languages-update' => 'Editujete jazyk: name',
    'languages-name' => 'Název jazyka',
    'languages-title' => 'Zadejte název jazyka',
    'languages-prefix' => 'Zkratka jazyka',
    'languages-prefix-title' => 'Zadejte zkratky jazyka (en, sk, de, cz) ...',
    'languages-po-name' => 'Překlad .po souboru pro Poedit',
    'languages-mo-name' => 'Překlad .mo souboru pro Poedit',
    'languages' => 'Jazykové mutace',
    'change-language' => 'Změna jazykové mutace. Pozor! Změna jazyka může zahodit Vaše aktuální rozepsané změny.',

    'show' => 'Zobrazit',
    'show-image' => 'Zobrazit obrázek',
    'download' => 'Stáhnout',
    'download-document' => 'Stáhnout dokument',
    'download-file' => 'Stáhnout soubor',

    'history.changes' => 'Historie změn',
    'history.who' => 'Změny provedl',
    'history.count' => 'Počet změn',
    'history.date' => 'Datum změny',

    'close' => 'Zavřít',
    'accept' => 'Potvrdit',
    'loading' => 'Načítám data ...',

    'created' => 'Vytvořeno',
    'created-at' => 'Vytvořené dne',
    'last-change' => 'Poslední změna',
    'published-at' => 'Publikované dne',

    'info' => 'Informace',
    'warning' => 'Upozornění',
    'row-info' => 'Informace o záznamu',
    'row-info-n' => 'Informace o záznamu č.',
    'no-changes' => 'V aktuálním záznamu nebyly provedeny žádné změny.',
    'delete-warning' => 'Opravdu chcete vymazat dany záznam?',

    'cannot-create' => 'Nelze přidat nový záznam.',
    'cannot-edit' => 'Tento záznam nelze upravovat.',
    'cannot-delete' => 'Tento záznam nelze vymazat.',
    'cannot-publish' => 'Tento záznam nelze znepublikovať.',
    'cannot-sort' => 'Tento záznam nelze přesouvat.',
    'success-created' => 'Záznam byl úspěšně přidán',
    'success-save' => 'Záznam byl úspěšně uložen',
    'with-errors' => 's následujícími chybami',

    'multilanguages' => 'Tento záznam je vícejazyčný',
    'rows' => 'Záznamy',
    'saving' => 'Ukládá se',
    'save' => 'Uložit',
    'send' => 'Odeslat',
    'sending' => 'Odesílání',
    'edit-row-n' => 'Upravit záznam č.',
    'new-row' => 'Nový záznam',
    'number' => 'č.',

    'edit' => 'Upravit',
    'show' => 'Zobrazit',
    'hide' => 'Skrýt',
    'delete' => 'Smazat',
    'delete-file' => 'Smazat Soubor',
    'select-option' => 'Vyberte jednu z možností',
    'select-option-multi' => 'Vyberte ze seznamu možností',
    'no-option' => 'Žádná možnost',

    'edit-size' => 'Upravte šířku zobrazení formuláře pro přehlednější zobrazení záznamů',
    'search' => 'Vyhledejte',
    'search-all' => 'Hledat všude',
    'get-value' => 'Vyberte hodnotu',
    'on' => 'Vypnuto',
    'off' => 'Zapnuto',
    'yes' => 'Ano',
    'no' => 'Ne',

    'rows-count' => 'Počet záznamů v tabulce',
    'show-all' => 'Zobrazit vše',
    'confirmation' => 'Ověření znovu',

    'success-save' => 'Změny byly úspěšně uloženy',
    'no-permissions' => 'nemá pravomoc na přistoupení do te sekcím.',
    'migrate-error' => 'Nastala Nečekané chyba, pravděpodobně jste nespustili migracím Modelové pomocí příkazu:',
    'db-error' => 'Nastala Nečekané chyba. Váš administrátor pravděpodobně zapomněl aktualizovat databázi. Pokud tato chyba přetrvává, kontaktujte ho. ',
    'row-error' => 'Záznam neexistuje, pravděpodobně již byl vymazán.',

    'login' => 'Přihlásit se',
    'password' => 'Heslo',
    'password-again' => 'Heslo znovu',
    'login-with' => 'Prosím, přihlaste se pomocí emailu a hesla',
    'remember-password' => 'Zapamatovat si',
    'forgot-password' => 'Zapomněl jsem heslo',
    'send-password' => 'Odeslat potvrzovací link na email',
    'password-reset' => 'Žádost o reset hesla',
    'password-reset-button' => 'Resetovat heslo',
];