<?php

return [
    'admin' => 'Administrace',
    'logout' => 'Odhlásit',
    'welcome' => 'Vítejte',
    'welcome-in-admin' => 'Vítejte v administraci',

    'auth-disabled' => 'Váš účet byl deaktivován.',
    'admin-user' => 'Administrátor',
    'auto-logout' => 'Byli jste automaticky odhlášeni. Prosím, přihlaste se znovu.',
    'unknown-error' => 'Nastala nečekaná chyba, zkuste později prosím.',

    'navigation' => 'Navigace',
    'language-mutation' => 'Jazykové verze',
    'language-title' => 'Upravte si nastavení jazykových mutací. Také si nastavte výchozí jazyk umístěním jazyka na první pozici.',
    'languages-add-new' => 'Přidat nový jazyk',
    'languages-update' => 'Editujete jazyk :name',
    'languages-name' => 'Název jazyka',
    'languages-title' => 'Zadejte název jazyka',
    'languages-prefix' => 'Zkratka jazyka',
    'languages-prefix-title' => 'Zadejte zkratky jazyka (en, sk, de, cz) ...',
    'languages-po-name' => 'Překlad .po souboru pro Poedit',
    'languages-mo-name' => 'Překlad .mo souboru pro Poedit',
    'languages' => 'Jazykové mutace',
    'languages-missing' => 'V administraci se nenacházejí žádné jazykové mutace, ke kterým by mohly být záznamy navázány. Prosím, přidejte alespoň jeden jazyk.',
    'change-language' => 'Změna jazykové mutace. Pozor! Změna jazyka může zahodit Vaše aktuální rozepsané změny.',

    'super-admin' => 'Super administrátor',
    'admin-group' => 'Administrátorská skupina',
    'user-groups' => 'Uživatelské skupiny',
    'user-groups-title' => 'Upravte uživatelské skupiny a jejich omezení',
    'user-groups-name' => 'Název skupiny',
    'user-groups-placeholder' => 'Zadejte název skupiny',
    'user-groups-modules' => 'Povolené moduly',

    'check-all' => 'Označit všechny',
    'uncheck-all' => 'Odznačit všechny',
    'show' => 'Zobrazit',
    'show-image' => 'Zobrazit obrázek',
    'download' => 'Stáhnout',
    'download-document' => 'Stáhnout dokument',
    'download-file' => 'Stáhnout soubor',

    'history.changes' => 'Historie změn',
    'history.who' => 'Změny provedl',
    'history.count' => 'Počet změn',
    'history.date' => 'Datum změny',
    'history.system' => 'Systém',
    'history.show' => 'Zobrazit změny',

    'close' => 'Zavřít',
    'accept' => 'Potvrdit',
    'loading' => 'Načítám data ...',

    'created' => 'Vytvořeno',
    'created-at' => 'Vytvořeno dne',
    'last-change' => 'Poslední změna',
    'published-at' => 'Publikováno dne',

    'info' => 'Informace',
    'warning' => 'Upozornění',
    'row-info' => 'Informace o záznamu',
    'row-info-n' => 'Informace o záznamu ID',
    'no-changes' => 'V aktuálním záznamu nebyly provedeny žádné změny.',
    'delete-warning' => 'Opravdu chcete smazat vybraný záznam?',

    'cannot-create' => 'Nelze přidat nový záznam.',
    'cannot-edit' => 'Tento záznam nelze upravit.',
    'cannot-delete' => 'Tento záznam nelze smazat.',
    'cannot-delete-multiple' => 'Jeden se záznamu nejde smazat.',
    'cannot-publish' => 'Tomunto záznamu nelze zrušit publikování.',
    'cannot-sort' => 'Tento záznam nelze přesunout.',
    'success-created' => 'Záznam byl úspěšně přidán.',
    'success-save' => 'Záznam byl úspěšně uložen',
    'with-errors' => 's následujícími chybami',

    'multilanguages' => 'Tento záznam je vícejazyčný',
    'rows' => 'Záznamy',
    'saving' => 'Ukládá se',
    'save' => 'Uložit',
    'send' => 'Odeslat',
    'sending' => 'Odesílání',
    'edit-row-n' => 'Upravit záznam ID',
    'new-row' => 'Nový záznam',
    'general-tab' => 'Obecné',
    'number' => 'ID',
    'rows-list' => 'Seznam sloupců',
    'default' => 'Výchozí',

    'edit' => 'Upravit',
    'show' => 'Zobrazit',
    'hide' => 'Skrýt',
    'action' => 'Akce',
    'publish-toggle' => 'Publikovat/Skrýt',
    'delete' => 'Smazat',
    'delete-file' => 'Smazat Soubor',
    'select-option' => 'Vyberte jednu z možností',
    'select-option-multi' => 'Vyberte ze seznamu možností',
    'no-option' => 'Žádná možnost',

    'edit-size' => 'Upravte šířku zobrazení formuláře pro přehlednější zobrazení záznamů',
    'search' => 'Vyhledat',
    'search-all' => 'Hledat všude',
    'get-value' => 'Vyberte hodnotu',
    'reset' => 'Resetovat',
    'on' => 'Zapnuto',
    'off' => 'Vypnuto',
    'yes' => 'Ano',
    'no' => 'Ne',

    'rows-count' => 'Počet záznamů v tabulce',
    'show-all' => 'Zobrazit vše',
    'confirmation' => 'Znovu ověření',

    'success-save' => 'Změny byly úspěšně uloženy',
    'no-permissions' => 'Pro přístup do tohoto modulu nemáte dostatečné oprávnění.',
    'migrate-error' => 'Nastala neočekávaná chyba, pravděpodobně jste nespustili migracím Modelové pomocí příkazu:',
    'db-error' => 'Nastala neočekávaná chyba. Váš administrátor pravděpodobně zapomněl aktualizovat databázi. Pokud tato chyba přetrvává, kontaktujte ho. ',
    'row-error' => 'Záznam neexistuje, pravděpodobně již byl vymazán.',
    'component-missing' => 'Komponenta s názvem <strong>%s</strong> pro vstup <strong>%s</strong> nebyl nalezen.',
    'lang-error' => 'Hodnoty výchozího jazyka jsou povinné. Prosíme, zkontrolujte vyplněné hodnoty.',

    'login' => 'Přihlásit se',
    'password' => 'Heslo',
    'password-again' => 'Heslo znovu',
    'login-with' => 'Prosím, přihlaste se pomocí emailu a hesla',
    'remember-password' => 'Zapamatovat si',
    'forgot-password' => 'Zapomněl jsem heslo',
    'send-password' => 'Odeslat potvrzovací link na email',
    'password-reset' => 'Žádost o reset hesla',
    'password-reset-button' => 'Resetovat heslo',
    'tab-error' => 'Záložka nemá vyplněné povinné údaje.',

    'gettext-open' => 'Upravit jazykové mutace',
    'gettext-update' => 'Upravit preklady',
    'gettext-search' => 'Vyhledávat pomocí výrazu',
    'gettext-no-match' => 'V prekladu nebyla nalezena žádná shoda.',
    'gettext-source' => 'Zdrojový text',
    'gettext-translation' => 'Překlad',
    'gettext-count' => 'Zobrazit všechny překlady',
    'gettext-loading' => 'Překlady se načitávajú, prosím počkejte.',
    'gettext-save' => 'Uložit a zavřít',
];