<?php

return [
    'admin'     => 'Administrácia',
    'logout'    => 'Odhlásiť sa',
    'welcome'   => 'Vitajte',
    'welcome-in-admin'   => 'Vitajte v administrácii',

    'admin-user'   => 'Administrátor',
    'auto-logout'   => 'Boli ste automatický odhlásený. Prosím, znova sa prihláste.',
    'unknown-error' => 'Nastala nečakana chyba, skúste neskôr prosím.',

    'navigation' => 'Navigácia',
    'language-mutation' => 'Jazyková verzia',
    'language-title' => 'Upravte si nastavenia jazykových mutácii. Taktiež si nastavte predvolený jazyk umiestnením jazyka na prvú pozíciu.',
    'languages-add-new' => 'Pridať nový jazyk',
    'languages-update' => 'Upravujete jazyk :name',
    'languages-name' => 'Názov jazyka',
    'languages-title' => 'Zadajte názov jazyka',
    'languages-prefix' => 'Skratka jazyka',
    'languages-prefix-title' => 'Zadajte skrátku jazyka (en, sk, de, cz)...',
    'languages-po-name' => 'Preklad .po súboru pre poedit',
    'languages-mo-name' => 'Preklad .mo súboru pre poedit',
    'languages' => 'Jazyková mutácia',
    'change-language' => 'Zmena jazykovej mutácie. Pozor! Zmena jazyka môže zahodiť Vaše aktuálne rozpísane zmeny.',

    'show' => 'Zobraziť',
    'show-image' => 'Zobraziť obrázok',
    'download' => 'Stiahnuť',
    'download-document' => 'Stiahnuť dokument',
    'download-file' => 'Stiahnuť súbor',

    'history.changes' => 'História zmien',
    'history.who' => 'Zmeny vykonal',
    'history.count' => 'Počet zmien',
    'history.date' => 'Dátum zmeny',

    'close' => 'Zatvoriť',
    'accept' => 'Potvrdiť',
    'loading' => 'Načítavam dáta...',

    'created' => 'Vytvorené',
    'created-at' => 'Vytvorené dňa',
    'last-change' => 'Posledná zmena',
    'published-at' => 'Publikované dňa',

    'info' => 'Informácia',
    'warning' => 'Upozornenie',
    'row-info' => 'Informácie o zázname',
    'row-info-n' => 'Informácie o zázname č.',
    'no-changes' => 'V aktuálnom zázname neboli vykonané žiadné zmeny.',
    'delete-warning' => 'Naozaj chcete vymazať dany záznam?',

    'cannot-create' => 'Nie je možné pridať nový záznam.',
    'cannot-edit' => 'Tento záznam nie je možné upravovať.',
    'cannot-delete' => 'Tento záznam nie je možné vymazať.',
    'cannot-publish' => 'Tento záznam nie je možné znepublikovať.',
    'cannot-sort' => 'Tento záznam nie je možné presúvať.',
    'success-created' => 'Záznam bol úspešne pridaný',
    'success-save' => 'Záznam bol úspešne uložený',
    'with-errors' => 's nasledujúcimi chybami',

    'multilanguages' => 'Tento záznam je viacjazyčný',
    'rows' => 'Záznamy',
    'saving' => 'Ukladá sa',
    'save' => 'Uložiť',
    'send' => 'Odoslať',
    'sending' => 'Odosiela sa',
    'edit-row-n' => 'Upraviť záznam č.',
    'new-row' => 'Nový záznam',
    'number' => 'č.',

    'edit' => 'Upraviť',
    'show' => 'Zobraziť',
    'hide' => 'Skryť',
    'delete' => 'Vymazať',
    'delete-file' => 'Vymazať súbor',
    'select-option' => 'Vyberte jednu z možností',
    'select-option-multi' => 'Vyberte zo zoznamu možností',
    'no-option' => 'Žiadna možnosť',

    'edit-size' => 'Upravte šírku zobrazenia formulára pre prehľadnejšie zobrazenie záznamov',
    'search' => 'Vyhľadajte',
    'search-all' => 'Hľadať všade',
    'get-value' => 'Vyberte hodnotu',
    'on' => 'Vypnuté',
    'off' => 'Zapnuté',
    'yes' => 'Áno',
    'no' => 'Nie',

    'rows-count' => 'Počet záznamov v tabuľke',
    'show-all' => 'Zobraziť všetko',
    'confirmation' => 'overenie znova',

    'success-save' => 'Zmeny boli úspešne uložené',
    'no-permissions' => 'Nemate právomoc k pristúpeniu do tejto sekcie.',
    'migrate-error' => 'Nastala nečakaná chyba, pravdepodobne ste nespústili migráciu modelov pomocou príkazu:',
    'db-error' => 'Nastala nečakaná chyba. Váš administrátor pravdepodobne zabudol aktualizovať databázu. Ak táto chyba pretrváva, kontaktujte ho.',
    'row-error' => 'Záznam neexistuje, pravdepodobne už bol vymazaný.',

    'login' => 'Prihlásiť sa',
    'password' => 'Heslo',
    'password-again' => 'Heslo znova',
    'login-with' => 'Prosím, prihláste sa pomocou emailu a hesla',
    'remember-password' => 'Zapamätať si',
    'forgot-password' => 'Zabudol som heslo',
    'send-password' => 'Odoslať potvrdzovací link na email',
    'password-reset' => 'Žiadosť o reset hesla',
    'password-reset-button' => 'Resetovať heslo',
    'tab-error' => 'Záložka nemá vyplnené povinné údaje.'
];